FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auditlog ./cmd/auditlog

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/auditlog /app/
COPY migrations /app/migrations
CMD ["/app/auditlog"]
