FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o gateway ./cmd/gateway

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway /app/
COPY migrations /app/migrations
CMD ["/app/gateway"]
